Controllers/FilesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TESS_GHOSTSTRIP_TRIAL.Data;
using TESS_GHOSTSTRIP_TRIAL.Models;
using TESS_GHOSTSTRIP_TRIAL.Services;

namespace TESS_GHOSTSTRIP_TRIAL.Controllers
{
    public class FilesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IOcrService _ocrService;
        private readonly IFileService _fileService;

        public FilesController(ApplicationDbContext context, IOcrService ocrService, IFileService fileService)
        {
            _context = context;
            _ocrService = ocrService;
            _fileService = fileService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchQuery)
        {
            var filesQuery = _context.fileMetadata.AsQueryable();

            if (!string.IsNullOrEmpty(searchQuery))
            {
                filesQuery = filesQuery
                    .Include(f => f.OcrResult)
                    .Where(f => f.FileName.Contains(searchQuery) ||
                                (f.OcrResult != null && f.OcrResult.ExtractedText.Contains(searchQuery)));
            }

            var files = await filesQuery.ToListAsync();

            // Pass the searchString to the view using ViewData
            ViewData["CurrentFilter"] = searchQuery;

            return View(files);
        }

        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                ModelState.AddModelError("File", "File is empty or not selected.");
                return View(); // Return with error message
            }

            var allowedContentTypes = new List<string> { "application/pdf", "image/jpeg", "image/jpg" };

            if (!allowedContentTypes.Contains(file.ContentType))
            {
                ModelState.AddModelError("File", "Unsupported file type.");
                return View(); // Return with error message
            }

            var uploadDate = DateTime.Now;
            var monthFolder = $"{uploadDate.ToString("MMMM")}_{uploadDate.Year.ToString()}";
            var dayFolder = $"{uploadDate.Month}-{uploadDate.Day}-{uploadDate.Year.ToString()}";

            var folderPath = Path.Combine(
               Directory.GetCurrentDirectory(),
               "wwwroot",
               "Documents Uploaded",
               uploadDate.Year.ToString(),
               monthFolder,
               dayFolder
            );

            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            var timestamp = DateTime.Now.ToString("yyyyMMddHHmmssfff");
            var uniqueFileName = $"{timestamp}_{Guid.NewGuid()}_{file.Name}";
            var filePath = Path.Combine(folderPath, uniqueFileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            byte[] fileData;
            string ocrResult = string.Empty;
            string fileName = file.FileName;

            using (var memoryStream = new MemoryStream())
            {
                await file.CopyToAsync(memoryStream);

                if (file.ContentType == "application/pdf")
                {
                    ocrResult = await _ocrService.ExtractTextFromPdfpigAsync(memoryStream);
                    fileData = await _fileService.PdfGhostscriptCompressionAsync(filePath);
                }
                else
                {
                    var performTesseract= await _ocrService.TesseractOcrAndSearchablePdfAsync(memoryStream, file.FileName);
                    ocrResult = performTesseract.OcrText;
                    fileName = performTesseract.PdfFileName;
                    fileData = performTesseract.PdfData;

                    fileData = await _fileService.ImageSharpCompressionAsync(memoryStream, 600, 800, 50);
                }

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await stream.WriteAsync(fileData, 0, fileData.Length);
                }

                // Save OCR result
                var ocrResultRecord = new OcrResult
                {
                    ExtractedText = ocrResult
                };

                // Save metadata and file data
                var uploadedFileMetadata = new FileMetadata
                {
                    FileName = fileName,
                    ContentType = file.ContentType,
                    Size = new FileInfo(filePath).Length,
                    FilePath = filePath,
                    UploadDate = uploadDate,
                    OcrResult = ocrResultRecord
                };

                var uploadedFileData = new FileData
                {
                    Data = fileData,
                    FileMetadata = uploadedFileMetadata
                };

                // Add ocr result, file metadata and file data to the database
                _context.ocrResults.Add(ocrResultRecord);
                _context.fileMetadata.Add(uploadedFileMetadata);
                _context.fileData.Add(uploadedFileData);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var file = await _context.fileMetadata
                .Include(f => f.OcrResult)
                .FirstOrDefaultAsync(f => f.Id == id);

            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        [HttpGet]
        public async Task<IActionResult> GetFile(int id)
        {
            var fileData = await _context.fileData
                .Include(fd => fd.FileMetadata)
                .FirstOrDefaultAsync(fd => fd.FileMetadataId == id);

            if (fileData == null)
            {
                return NotFound();
            }

            var contentType = fileData.FileMetadata.ContentType;
            var fileName = fileData.FileMetadata.FileName;

            Response.Headers.Append("Content-Disposition", $"inline; filename={fileName}");
            return File(fileData.Data, contentType);

            //if (contentType.StartsWith("image/"))
            //{
            //    // Create searchable PDF from image data
            //    //using (var memoryStream = new MemoryStream(fileData.Data))
            //    //{
            //    //    //var pdfBytes = await _ocrService.ImageToSearchablePdfAsync(memoryStream, fileName);

            //    //    // Set the response to download the PDF
            //    //    Response.Headers.Append("Content-Disposition", $"attachment; filename={Path.GetFileNameWithoutExtension(fileName)}.pdf");
            //    //    return File(pdfBytes, "application/pdf");
            //    //}
        }
    }
}

Views/Files/Details.cshtml
@model FileMetadata

@{
    ViewData["Title"] = @Model.FileName;
}

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title text-center">@Model.FileName</h3>
    </div>
    <div class="panel-body">
        <h5 class="card-subtitle text-muted">Uploaded Date: @Model.UploadDate</h5>
        <h6 class="card-subtitle text-muted">Content Type: @Model.ContentType</h6>
        <p><strong>Size:</strong> @Model.FormattedSize</p>
        <iframe src="@Url.Action("GetFile", "Files", new { id = Model.Id })" width="100%" height="800px"></iframe>
    </div>

    <div class="form-group">
        <label>Result:</label>
        @if (Model.OcrResult == null || string.IsNullOrEmpty(Model.OcrResult.ExtractedText))
        {
            <p>No OCR result available.</p>
        }
        else
        {
            <textarea class="form-control" rows="15" readonly>@Model.OcrResult.ExtractedText</textarea>
        }
    </div>

</div>

Views/Files/Index.cshtml
@model IEnumerable<FileMetadata>

@{
    ViewData["Title"] = "Documents";
}

<h2>@ViewData["Title"]</h2>

<a asp-action="Upload" class="btn btn-success"><i class="bi bi-plus-circle"></i> Upload New File</a>
<br />
<br />

<form asp-action="Index" method="get">
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="searchQuery" placeholder="Search by file name or OCR content" value="@ViewData["CurrentFilter"]" />
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
        </div>
    </div>
</form>

<div class="panel panel-primary">
    <div class="panel-heading text-center">DOCUMENT LIST</div>
    <div class="panel-body">
        <table class="table table-striped-columns">
            <thead>
                <tr class="info">
                    <th>File Name</th>
                    <th>Upload Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Any())
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.FileName</td>
                            <td>@item.UploadDate.ToString("MM/dd/yyyy")</td>
                            <td>
                                <a asp-controller="Files" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">View</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="3" class="text-center">No files found.</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Files/Upload.cshtml
@{
    ViewData["Title"] = "Upload File";
}

<h2>Upload File</h2>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">@TempData["SuccessMessage"]</div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<form asp-action="Upload" asp-controller="Files" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="file" aria-label="Choose a file (PDF/Image)">Choose a file (PDF/Image):</label>
        <input type="file" name="file" class="form-control" accept=".pdf, .jpg, .jpeg, .png" required />
        <small class="form-text text-muted">Supported file types: PDF, JPG, JPEG.</small>
    </div>
    <div class="form-group">
        <input type="submit" value="Upload and Perform OCR" class="btn btn-primary" />
    </div>
</form>